### PR TITLE
Traduction 0.2.6

### PR DESCRIPTION
**Pull request by ZolOnTheNet**
Hello, I added some translations (lines 188,189) that I didn't have in fr.yml and I found more expressive lines (142-145) in French.

Just to have an opinion, in the French rules, "Intellect" is translated as "Intelligence", but in the character sheet, it doesn't look very nice. Intellect is perfectly acceptable in French.

What do you think?

### CODE REVIEW

**Comment by Assembling-Kings** [comment]
Thanks again for the contribution!

1- This PR has conflicts with the main branch. Can you sync your repository and make sure you use the latest commit to create the translation branch. Then create a PR with that new branch.
2- I think using "Intellect" instead of "Intelligence" is a good idea if it keeps the sheet looking nice.

**Comment by ZolOnTheNet** [comment]
Dam! I thought I had!, I try again

**Comment by ZolOnTheNet** [comment]
And now ?

**Comment by Assembling-Kings** [comment]
Yeah, now it seems fine, ty.

**Pull request merged**
